Often the tabular data we need is inside PDFs. One or two pages can be manually copy pasted into excel sheet. But when we have to deal with huge PDFs, then manual method won't suffice. 

There are a few websites like ilovepdf.com that help in converting PDFs to Excel Sheets. These are really powerful tools and mostly our requirement could be achieved from them. 

But, if at all you need control on how to build a dataframe from the table in PDF. Or if you want to automate the process, you should be able to code it. 

[Camelot](https://camelot-py.readthedocs.io/en/master/) comes to our rescue!

[This article](https://github.com/atlanhq/camelot/wiki/Comparison-with-other-PDF-Table-Extraction-libraries-and-tools)  compared Camelot with other PDF-extracters and concluded that Camelot works better than any other in most cases. So, we are going ahead with this.

In [1]:
!pip install camelot-py

Collecting camelot-py
  Downloading camelot_py-0.8.2-py3-none-any.whl (42 kB)
Requirement already satisfied: openpyxl>=2.5.8 in c:\users\saikr\anaconda3\lib\site-packages (from camelot-py) (3.0.4)
Requirement already satisfied: click>=6.7 in c:\users\saikr\anaconda3\lib\site-packages (from camelot-py) (7.1.2)
Collecting PyPDF2>=1.26.0
  Downloading PyPDF2-1.26.0.tar.gz (77 kB)
Requirement already satisfied: pandas>=0.23.4 in c:\users\saikr\anaconda3\lib\site-packages (from camelot-py) (1.1.3)
Collecting pdfminer.six>=20200726
  Downloading pdfminer.six-20201018-py3-none-any.whl (5.6 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\saikr\anaconda3\lib\site-packages (from camelot-py) (1.19.2)
Requirement already satisfied: chardet>=3.0.4 in c:\users\saikr\anaconda3\lib\site-packages (from camelot-py) (3.0.4)
Requirement already satisfied: jdcal in c:\users\saikr\anaconda3\lib\site-packages (from openpyxl>=2.5.8->camelot-py) (1.4.1)
Requirement already satisfied: et-xmlfile in c:\users\saikr\anaconda3\lib\site-packages (from openpyxl>=2.5.8->camelot-py) (1.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\saikr\anaconda3\lib\site-packages (from pandas>=0.23.4->camelot-py) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\saikr\anaconda3\lib\site-packages (from pandas>=0.23.4->camelot-py) (2020.1)
Requirement already satisfied: cryptography in c:\users\saikr\anaconda3\lib\site-packages (from pdfminer.six>=20200726->camelot-py) (2.9.2)
Requirement already satisfied: sortedcontainers in c:\users\saikr\anaconda3\lib\site-packages (from pdfminer.six>=20200726->camelot-py) (2.2.2)
Requirement already satisfied: six>=1.5 in c:\users\saikr\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23.4->camelot-py) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\saikr\anaconda3\lib\site-packages (from cryptography->pdfminer.six>=20200726->camelot-py) (1.14.0)
Requirement already satisfied: pycparser in c:\users\saikr\anaconda3\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography->pdfminer.six>=20200726->camelot-py) (2.20)
Building wheels for collected packages: PyPDF2
  Building wheel for PyPDF2 (setup.py): started
  Building wheel for PyPDF2 (setup.py): finished with status 'done'
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61087 sha256=61321664f230692b424b6c937eea9b87162e34551a3443d4983e9fef529532c1
  Stored in directory: c:\users\saikr\appdata\local\pip\cache\wheels\b1\1a\8f\a4c34be976825a2f7948d0fa40907598d69834f8ab5889de11
Successfully built PyPDF2
Installing collected packages: PyPDF2, pdfminer.six, camelot-py
Successfully installed PyPDF2-1.26.0 camelot-py-0.8.2 pdfminer.six-20201018

In [9]:
pip install ghostscript

Collecting ghostscriptNote: you may need to restart the kernel to use updated packages.
  Downloading ghostscript-0.6-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: setuptools in c:\users\saikr\anaconda3\lib\site-packages (from ghostscript) (50.3.0)
Installing collected packages: ghostscript
Successfully installed ghostscript-0.6

# Reading the PDFs.
In this tutorial, I am going to work with [National Health Profile-2019 PDF](https://www.thehinducentre.com/resources/article29841374.ece/binary/8603321691572511495.pdf).

In [3]:
import pandas as pd

import camelot

ModuleNotFoundError: No module named 'cv2'

In [10]:
pdf_url = "https://www.thehinducentre.com/resources/article29841374.ece/binary/8603321691572511495.pdf"

#Downloading the PDF 
!wget https://www.thehinducentre.com/resources/article29841374.ece/binary/8603321691572511495.pdf

--2020-04-24 07:37:49--  https://www.thehinducentre.com/resources/article29841374.ece/binary/8603321691572511495.pdf
Resolving www.thehinducentre.com (www.thehinducentre.com)... 104.17.37.68, 104.17.38.68, 2606:4700::6811:2544, ...
Connecting to www.thehinducentre.com (www.thehinducentre.com)|104.17.37.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/pdf]
Saving to: ‘8603321691572511495.pdf.1’

8603321691572511495     [ <=>                ]   4.54M  --.-KB/s    in 0.04s

2020-04-24 07:37:49 (111 MB/s) - ‘8603321691572511495.pdf.1’ saved [4759317]

In [0]:
pdf_file = "/content/8603321691572511495.pdf"

In [17]:
tables = camelot.read_pdf(pdf_file, flavor='lattice', pages='289,290')
tables

In [20]:
type(tables)

camelot.core.TableList

We passed in only two pages from the PDF. You can also write 'all' to pass in the entire PDF.

There are two modes of extraction in Camelot. Lattice and Stream. In Lattice, PDFs with clearly delineated tables are extracted. Since our tables are well delineated in the PDF, we will use Lattice. 

TableList n=2. This shows the number of tables extracted from the PDF. All these tables are in a list. 

**NOTE**: If the PDF is password protected, use password argument inside read_pdf

In [21]:
tables[0]

To know how well the table was extracted, use parsing report.
High accuracy and low whitespace is what we need.

In [23]:
print(tables[0].parsing_report)

{'accuracy': 100.0, 'whitespace': 0.53, 'order': 1, 'page': 289}

In [26]:
tables[0].df

         0                  1            2      3     4
0   S. No.          States/UT  Sub Centres   PHCs  CHCs
1                       India       158417  25743  5624
2        1     Andhra Pradesh         7458   1147   193
3        2  Arunachal Pradesh          312    143    63
4        3              Assam         4644    946   172
5        4              Bihar         9949   1899   150
6        5       Chhattisgarh         5200    793   169
7        6                Goa          214     25     4
8        7            Gujarat         9153   1474   363
9        8            Haryana         2589    368   113
10       9   Himachal Pradesh         2084    576    91
11      10    Jammu & Kashmir         2967    637    84
12      11          Jharkhand         3848    298   171
13      12          Karnataka         9443   2359   206
14      13             Kerala         5380    849   227
15      14     Madhya Pradesh        11192   1171   309
16      15        Maharashtra        10638   1823   361
17      16            Manipur          429     91    23
18      17          Meghalaya          443    108    28
19      18            Mizoram          370     57     9
20      19           Nagaland          396    126    21
21      20             Odisha         6688   1288   377
22      21             Punjab         2950    432   151
23      22          Rajasthan        14405   2078   588
24      23             Sikkim          147     24     2
25      24         Tamil Nadu         8712   1421   385
26      25          Telangana         4744    643    91
27      26            Tripura         1020    108    22
28      27        Uttarakhand         1847    257    67
29      28      Uttar Pradesh        20521   3621   822
30      29       West Bengal*        10357    913   348
31      30       A& N Islands          123     22     4
32      31         Chandigarh           17      0     0
33      32       D & N Haveli           71      9     2
34      33        Daman & Diu           26      4     2
35      34              Delhi           12      5     0
36      35        Lakshadweep           14      4     3
37      36         Puducherry           54     24     3

In [27]:
tables[1].df

           0                   1  ...       7                   8
0   S. \nNo.   State/UT/Division  ...          Reference \nPeriod
1                                 ...    Beds
2                                 ...
3                          India  ...  713986
4          1      Andhra Pradesh  ...   23138          01.01.2017
5          2  Arunachal Pradesh*  ...    2404          31.12.2018
6          3             Assam *  ...   17142          31.12.2017
7          4               Bihar  ...   11664          31.12.2018
8          5        Chhattisgarh  ...    9412          01.01.2016
9          6                Goa*  ...    3012          31.12.2018
10         7             Gujarat  ...   20172          31.12.2018
11         8            Haryana*  ...   11240          31.12.2016
12         9   Himachal Pradesh*  ...   12399          31.12.2017
13        10     Jammu & Kashmir  ...    7291          31.12.2018
14        11           Jharkhand  ...   10784          31.12.2015
15        12          Karnataka*  ...   69721          31.12.2018
16        13              Kerala  ...   38004          01.01.2017
17        14      Madhya Pradesh  ...   31106          01.01.2018
18        15         Maharashtra  ...   51446          31.12.2015
19        16             Manipur  ...    1427          01.01.2014
20        17          Meghalaya*  ...    4457          31.12.2017
21        18            Mizoram*  ...    1997          31.12.2017
22        19            Nagaland  ...    1880          31.12.2015
23        20             Odisha*  ...   18519          31.12.2018
24        21             Punjab*  ...   17933          31.12.2017
25        22         Rajasthan *  ...   47054          31.12.2018
26        23             Sikkim*  ...    1560          31.12.2017
27        24         Tamil Nadu*  ...   77532          31.12.2017
28        25          Telangana*  ...   20983          31.12.2017
29        26            Tripura*  ...    4429          31.12.2018
30        27      Uttar Pradesh*  ...   76260          31.12.2017
31        28         Uttarakhand  ...    8512          31.12.2015
32        29         West Bengal  ...   78566          01.01.2015
33        30          A&N Island  ...    1075          31.12.2016
34        31          Chandigarh  ...    3756          31.12.2018
35        32         D&N Haveli*  ...     619          31.12.2018
36        33         Daman & Diu  ...     240          31.12.2015
37        34               Delhi  ...   24383          01.01.2015
38        35         Lakshadweep  ...     300          01.01.2016
39        36          Puducherry  ...    3569          01.01.2016

[40 rows x 9 columns]

In [28]:
print(tables[1].parsing_report)

{'accuracy': 99.57, 'whitespace': 4.72, 'order': 1, 'page': 290}

# Saving PDFs as CSVs

In [0]:
tables.export('Health_Infra.csv', f='csv')
# json, html, excel, sqlite are also possible